## This file contains files and directories that should
## be preserved during an upgrade.

# /etc/example.conf
# /etc/openvpn/
/usr/libexec/rpcd/campus-dashboard
/www/luci-static/resources/view/campus/dashboard.js
/usr/share/luci/menu.d/luci-campus-dashboard.json
/usr/share/rpcd/acl.d/luci-app-campus-dashboard.json
/etc/adblock-small.hosts
/usr/libexec/rpcd/adblock-small
/www/luci-static/resources/view/campus/adblock.js
/usr/share/luci/menu.d/luci-adblock-small.json
/usr/share/rpcd/acl.d/luci-adblock-small.json
/etc/adblock-small.source.hosts
/etc/adblock-small.allow
/etc/wireguard/
/usr/libexec/rpcd/dorm-pc
/www/luci-static/resources/view/campus/dorm-pc.js
/usr/share/luci/menu.d/luci-dorm-pc.json
/usr/share/rpcd/acl.d/luci-dorm-pc.json
/etc/hotplug.d/iface/95-campus-admin-return
