#!/bin/sh
case "$1:$2" in
 list:*) echo '{"status":{},"wake":{}}';;
 call:status)
   if ping -c 1 -W 1 192.168.1.212 >/dev/null 2>&1; then echo '{"online":true}'; else echo '{"online":false}'; fi;;
 call:wake)
   if /usr/bin/etherwake -i br-lan -b 10:FF:E0:E7:C0:F2 >/dev/null 2>&1; then echo '{"ok":true}'; else echo '{"ok":false}'; fi;;
esac
